DROP TABLE FILE_BOARD CASCADE CONSTRAINTS;
DROP SEQUENCE FILE_SEQ;
DROP SEQUENCE DOWN_SEQ;
DROP SEQUENCE RATE_SEQ;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;

create table FILE_BOARD(
    NO number CONSTRAINT PK_FILE primary key,
    ORIGIN_NAME varchar2(210) not null,
    SAVE_NAME varchar2(210) not null,
    FILE_TYPE varchar2(30),
    FILE_SIZE NUMBER not null,
    FILE_UPLOADER varchar2(96),
    DOWN_COUNT NUMBER,
    RATE NUMBER
);
CREATE SEQUENCE FILE_SEQ START WITH 0 MINVALUE 0 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DOWN_SEQ START WITH 0 MINVALUE 0 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RATE_SEQ START WITH 0 MINVALUE 0 INCREMENT BY 1 NOCACHE;

CREATE TABLE MEMBERS(
    MEM_ID VARCHAR2(96) CONSTRAINT PK_MEMBERS PRIMARY KEY,
    MEM_PWD VARCHAR2(80) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(640) CONSTRAINT UQ_MEMBERS UNIQUE NOT NULL,
    GENDER VARCHAR2(12) CONSTRAINT CK_MEMBERS CHECK (GENDER IN('MALE','FEMALE')),
    PHONE NUMBER(12),
    CR_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE FILE_BOARD ADD CONSTRAINT FK_FILE_BOARD
	FOREIGN KEY(FILE_UPLOADER) REFERENCES MEMBERS (MEM_ID) ON DELETE CASCADE;

insert into members(MEM_ID,MEM_PWD,NAME,EMAIL) values('admin','java0829','주인장','admin@members.com');

